import pyautogui as pag
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# 0. chrome driver 다운로드
pag.hotkey('win', 's')
pag.write('chrome')
time.sleep(0.5)
pag.press('enter')
time.sleep(2)
pag.hotkey('alt', 'space')
time.sleep(1)
pag.press('x')
time.sleep(1)
pag.moveTo(430, 99, 1)
pag.click()
time.sleep(3)
pag.moveTo(615, 788, 1)
pag.click()
time.sleep(0.5)
pag.press('tab')
time.sleep(0.5)
pag.press('enter')
time.sleep(0.5)
pag.hotkey('alt', 'F4')
pag.moveTo(300, 52, 1)
time.sleep(0.5)
pag.click()
pag.write('https://chromedriver.chromium.org/downloads')
time.sleep(0.5)
pag.press('enter')
time.sleep(0.5)
pag.moveTo(978, 300, 1)
pag.click()
pag.moveTo(978, 392, 0.2)
pag.click()
time.sleep(0.5)
pag.moveTo(159, 298, 2)
pag.click()
time.sleep(0.5)
pag.moveTo(101, 1013, 2)
pag.click()
time.sleep(0.5)
pag.moveTo(1670, 434, 2)
pag.click()
time.sleep(0.5)
pag.write('chrome')
pag.moveTo(1004, 497, 0.2)
pag.click()
pag.hotkey('ctrl', 'c')
pag.doubleClick()
time.sleep(2)
pag.hotkey('alt', 'F4')
time.sleep(1)
pag.moveTo(1182, 432, 1)
pag.click()
time.sleep(1)
pag.write('C:\\Users\\CKIRUser\\AppData\\Local\\Programs\\Python\\Python39')
pag.press('enter')
pag.moveTo(1704, 916, 1)
pag.click()
pag.hotkey('ctrl', 'v')
time.sleep(1)
pag.click()
pag.hotkey('alt', 'F4')
time.sleep(1)

# vscode 다운로드
pag.hotkey('win', 's')
pag.write('chrome')
time.sleep(0.5)
pag.press('enter')
time.sleep(1)
pag.hotkey('alt', 'space', 'x')
pag.moveTo(300, 52, 1)
time.sleep(0.5)
pag.click()
pag.write('https://code.visualstudio.com/')
time.sleep(0.5)
pag.press('enter')
pag.moveTo(540, 434, 3)
pag.click()
pag.moveTo(104, 1013, 1)
time.sleep(60)
pag.click()
time.sleep(5)
pag.press('enter')
time.sleep(5)
pag.hotkey('Alt', 'a')
time.sleep(1)
pag.press('enter', presses=3, interval=1)
time.sleep(20)
pag.press('enter')
time.sleep(5)
pag.hotkey('Alt', 'F4')
time.sleep(3)
pag.hotkey('ctrl', 'w')
time.sleep(1)
pag.hotkey('ctrl', 'w')